all: writeFASTfiles.f90
	ftn -o FASTfilesWrite writeFASTfiles.f90
#	ifort -o FASTfilesWrite writeFASTfiles.f90 # Use sizeOfReal=1 in intel. Reads in words.
#	pgf90 -o FASTfilesWrite writeFASTfiles.f90 # Use sizeOfReal=4 in pgi. Reads in bytes.
