#!/bin/sh
# This must be /bin/sh (other shells do not work)
# Run 15 copies of ./FASTfilesWrite in the background

# ./FASTfilesWrite 1 1 &> log.FASTfilesWrite_1_1 &
./FASTfilesWrite 2 2 &> log.FASTfilesWrite_2_2 &
./FASTfilesWrite 3 3 &> log.FASTfilesWrite_3_3 &
./FASTfilesWrite 4 4 &> log.FASTfilesWrite_4_4 &
./FASTfilesWrite 5 5 &> log.FASTfilesWrite_5_5 &
./FASTfilesWrite 6 6 &> log.FASTfilesWrite_6_6 &
./FASTfilesWrite 7 7 &> log.FASTfilesWrite_7_7 &
./FASTfilesWrite 8 8 &> log.FASTfilesWrite_8_8 &
./FASTfilesWrite 9 9 &> log.FASTfilesWrite_9_9 &
./FASTfilesWrite 10 10 &> log.FASTfilesWrite_10_10 &
./FASTfilesWrite 11 11 &> log.FASTfilesWrite_11_11 &
./FASTfilesWrite 12 12 &> log.FASTfilesWrite_12_12 &
./FASTfilesWrite 13 13 &> log.FASTfilesWrite_13_13 &
./FASTfilesWrite 14 14 &> log.FASTfilesWrite_14_14 &
./FASTfilesWrite 15 15 &> log.FASTfilesWrite_15_15 &
wait
# Wait until all copies of FASTfilesWrite have finished

